//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cheku {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class BGSystemSetting : global::System.Configuration.ApplicationSettingsBase {
        
        private static BGSystemSetting defaultInstance = ((BGSystemSetting)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new BGSystemSetting())));
        
        public static BGSystemSetting Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("单主机")]
        public string SystemMode {
            get {
                return ((string)(this["SystemMode"]));
            }
            set {
                this["SystemMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ServerAddr {
            get {
                return ((string)(this["ServerAddr"]));
            }
            set {
                this["ServerAddr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Rs485Port {
            get {
                return ((string)(this["Rs485Port"]));
            }
            set {
                this["Rs485Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string TotalSpace {
            get {
                return ((string)(this["TotalSpace"]));
            }
            set {
                this["TotalSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string OccupiedSpace {
            get {
                return ((string)(this["OccupiedSpace"]));
            }
            set {
                this["OccupiedSpace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public string RemainSpace {
            get {
                return ((string)(this["RemainSpace"]));
            }
            set {
                this["RemainSpace"] = value;
            }
        }
    }
}
